config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users
  resources :cocktail_recipes do
    member do
      put 'like', to: 'cocktail_recipes#like'
      put 'unlike', to: 'cocktail_recipes#unlike'
    end
  end
  root to: 'cocktail_recipes#index'
  resources :ingredients, only: %i[index show]
  resources :ingredient_categories, only: %i[index show]

end

app/models/cocktail_recipe.rb
# frozen_string_literal: true

# from http://stackoverflow.com/a/36134208/1796645
class CollectionLengthValidator < ActiveModel::Validations::LengthValidator
  def validate_each(record, attribute, value)
    value = value.respond_to?(:reject) ? value.reject(&:marked_for_destruction?) : value
    super(record, attribute, value)
  end
end

# This Model represents a Cocktail Recipe
# name
# cocktail_recipe_parts
class CocktailRecipe < ApplicationRecord
  PROFIT_MARGIN = 1.03

  alias_attribute :parts, :cocktail_recipe_parts
  has_many :cocktail_recipe_parts, dependent: :destroy
  accepts_nested_attributes_for :cocktail_recipe_parts, reject_if: :all_blank, allow_destroy: true

  has_many :user_cocktail_likes, dependent: :destroy
  has_many :users, through: :user_cocktail_likes

  alias_attribute :liking_users, :users

  ## validations
  validates :name, presence: true, uniqueness: true
  validates :cocktail_recipe_parts, collection_length: { minimum: 2 }

  ## scopes
  scope :liked, -> { joins(:user_cocktail_likes).distinct }
  scope :liked_sorted, lambda {
    # inspired from https://stackoverflow.com/a/22235146/1796645
    select('cocktail_recipes.*, COUNT(user_cocktail_likes.id) vote_count')
      .joins(:user_cocktail_likes)
      .group('cocktail_recipes.id')
      .order('vote_count DESC')
  }

  def cost
    cocktail_recipe_parts.sum(&:cost).round(2)
  end

  def selling_price
    (cost * PROFIT_MARGIN).round(1)
  end

  def likes
    user_cocktail_likes.count
  end

  # @return [Array] Collection of (unpersisted) CocktailRecipe objects
  def alternatives
    return CocktailRecipe.none if very_strict?

    VariantsCalculator.new(parts).part_combinations.map do |variant|
      self.class.new(name: variant.map(&:ingredient_name).join(', '), parts: variant)
    end
  end

  private

  def very_strict?
    parts.all?(&:strict?)
  end
end

app/controllers/cocktail_recipes_controller.rb
# frozen_string_literal: true

class CocktailRecipesController < ApplicationController
  before_action :set_cocktail_recipe, only: %i[show edit update destroy like unlike]
  before_action :authenticate_admin!, only: %i[new create edit update destroy]

  def index
    @cocktail_recipes =
      CocktailRecipe.includes(cocktail_recipe_parts: %i[ingredient ingredient_category]).all
  end

  def show; end

  def new
    @cocktail_recipe = CocktailRecipe.new
  end

  def edit; end

  def create
    @cocktail_recipe = CocktailRecipe.new(cocktail_recipe_params)

    respond_to do |format|
      if @cocktail_recipe.save
        format.html { redirect_to @cocktail_recipe, notice: 'Cocktail recipe was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail_recipe }
      else
        format.html { render :new }
        format.json { render json: @cocktail_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cocktail_recipe.update(cocktail_recipe_params)
        format.html { redirect_to @cocktail_recipe, notice: 'Cocktail recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail_recipe }
      else
        format.html { render :edit }
        format.json { render json: @cocktail_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cocktail_recipe.destroy
    respond_to do |format|
      format.html { redirect_to cocktail_recipes_url, notice: 'Cocktail recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    respond_to do |format|
      if current_user.like_cocktail(@cocktail_recipe).persisted?
        format.html { redirect_to @cocktail_recipe, notice: 'Liked that cocktail!' }
        format.json { render :show, status: :ok, location: @cocktail_recipe }
      else
        format.html { render :show, status: :internal_server_error, notice: 'went wrong' }
        format.json { render json: @cocktail_recipe.errors, status: :internal_server_error }
      end
    end
  end

  def unlike
    respond_to do |format|
      if current_user.unlike_cocktail(@cocktail_recipe).persisted?
        format.html { redirect_to @cocktail_recipe, notice: 'Liked that cocktail!' }
        format.json { render :show, status: :ok, location: @cocktail_recipe }
      else
        format.html { render :show, status: :internal_server_error, notice: 'went wrong' }
        format.json { render json: @cocktail_recipe.errors, status: :internal_server_error }
      end
    end
  end

  private

  def set_cocktail_recipe
    @cocktail_recipe = CocktailRecipe.find(params[:id])
  end

  def cocktail_recipe_params
    params.require(:cocktail_recipe).permit(
      :name,
      :description,
      cocktail_recipe_parts_attributes: %i[id ingredient_id strict amount _destroy]
    )
  end
end

app/views/cocktail_recipes/_form.html.haml
= simple_form_for(@cocktail_recipe) do |f|
  - if @cocktail_recipe.errors.any?
    #error_explanation
      %h2
        = pluralize(@cocktail_recipe.errors.count, 'error')
        prohibited this cocktail_recipe from being saved:
      %ul
        - @cocktail_recipe.errors.full_messages.each do |message|
          %li= message
  .field
    = f.input :name
  %h3 Ingredients:
  = f.simple_fields_for :cocktail_recipe_parts do |recipe_parts_form|
    = render 'recipe_part_fields', f: recipe_parts_form
  .links
    = link_to_add_association 'add ingredient', f, :cocktail_recipe_parts, partial: 'recipe_part_fields'
  .field
    = f.input :description
  .actions
    = f.button :submit

app/views/cocktail_recipes/_recipe_part_fields.html.haml
.nested-fields
  .field
    = f.association :ingredient, collection: IngredientCategory.all,        |
      as: :grouped_select, group_method: :ingredients, include_blank: false |
    = f.input :strict
  .field
    = f.input :amount
  = link_to_remove_association 'remove ingredient', f

app/views/cocktail_recipes/edit.html.haml
%h1 Editing Cocktail Recipe
= render 'form'
= link_to 'Show', @cocktail_recipe
|
= link_to 'Back', cocktail_recipes_path

app/views/cocktail_recipes/index.html.haml
%p#notice= notice
%h1 Listing Cocktail Recipes
.uk-grid.uk-flex-around.data-uk-grid-match{class: 'uk-child-width-1-2@s uk-child-width-1-3@m uk-child-width-1-4@l'}
  - @cocktail_recipes.each do |cocktail_recipe|
    = render CocktailRecipeComponent.new(recipe: cocktail_recipe, admin_signed_in: admin_signed_in?)
%br/
= link_to_if admin_signed_in?, 'New Cocktail recipe', new_cocktail_recipe_path

app/views/cocktail_recipes/new.html.haml
%h1 New Cocktail Recipe
= render 'form'
= link_to 'Back', cocktail_recipes_path

app/views/cocktail_recipes/show.html.haml
%p#notice= notice
%h1.uk-heading-primary
  = @cocktail_recipe.name
.uk-grid.uk-grid-divider
  - if @cocktail_recipe.cocktail_recipe_parts
    .uk-width-xlarge
      %h2 Ingredients:
      %table.uk-table.uk-table-responsive.uk-table-divider.uk-table-hover
        %thead
          %tr
            %th.uk-table-shrink Amount
            %th Part
        %tbody
          - @cocktail_recipe.cocktail_recipe_parts.each do |recipe_part|
            %tr
              %td
                = recipe_part.amount
                ml
              %td
                - if recipe_part.strict
                  = recipe_part.ingredient_name
                - else
                  = recipe_part.category_name
                  ,
                  %strong default:
                  = recipe_part.ingredient_name
  .uk-width-xlarge
    %dl.uk-description-list
      %dt Selling price
      %dd
        = number_to_currency @cocktail_recipe.selling_price, unit: '€'
      %dt Cost
      %dd
        = @cocktail_recipe.cost
      %dt Description
      %dd.uk-text-break
        = @cocktail_recipe.description
- if user_signed_in?
  - if current_user.likes_cocktail? @cocktail_recipe
    = link_to 'UNLIKE', unlike_cocktail_recipe_path(@cocktail_recipe), method: :put
  - else
    = link_to 'LIKE', like_cocktail_recipe_path(@cocktail_recipe), method: :put
- if admin_signed_in?
  = link_to 'Edit', edit_cocktail_recipe_path(@cocktail_recipe)
  |
  \#{link_to 'Back', cocktail_recipes_path}
%br
%br
.uk-grid
  .uk-width-xlarge
    %dt Alternative Prices
    %div
      %table.uk-table.uk-table-responsive.uk-table-divider.uk-table-hover
        %thead
          %tr
            %th.uk-table-shrink Price
            %th Ingredient combination
        %tbody
          - @cocktail_recipe.alternatives.each do |recipe_alternative|
            %tr
              %td
                = number_to_currency recipe_alternative.selling_price, unit: '€'
              %td
                = recipe_alternative.name