config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  devise_for :admins
  devise_for :users
  resources :cocktail_recipes do
    member do
      put 'like', to: 'cocktail_recipes#like'
      put 'unlike', to: 'cocktail_recipes#unlike'
    end
  end
  root to: 'cocktail_recipes#index'
  resources :ingredients, only: %i[index show]
  resources :ingredient_categories, only: %i[index show]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type'}/
    %title LazyBar
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track': true
    = csrf_meta_tags
  %body
    .uk-container.uk-container-large
      %p.notice
        = notice
      %p.alert
        = alert
      %ul.uk-tab
        %li= link_to 'Kategorien', ingredient_categories_path
        %li= link_to 'Zutaten', ingredients_path
        %li= link_to 'Cocktails', cocktail_recipes_path
        - if signed_in?
          - if user_signed_in?
            | Logged in as:
            \#{current_user.email}
            \#{link_to('Logout', destroy_user_session_path, :method => :delete)}
          - if admin_signed_in?
            | Logged in as:
            \#{current_admin.email}
            \#{link_to('Logout', destroy_admin_session_path, :method => :delete)}
        - else
          %li|
          %li= link_to('User Login', new_user_session_path)
          %li= link_to('Admin Login', new_admin_session_path)
      = yield
    %br
    .uk-container.uk-container-large
      %p.disclaimer
        Personal project, open source.
        \#{link_to 'Source Code', 'https://github.com/klyonrad/lazybar'}